### ISSUE TITLE
WireContainerType and TreeContainerType are differently implemented

### ISSUE THREAD

**Issue by foolswood** [concert/clapi#105]
The wire one has 2 arguments, the tree has 1.
Is one better than the other, should we consolidate etc?

**Comment by ch3pjw** [comment]
I don't think the `WireType` is as recent/as good. I've been wondering whether with my changes where we don't need to differentiate between container types and regular types so much (because the proxying stuff is more generic) we can consolidate a bunch of stuff like this.

See latest on https://github.com/concert/clapi/tree/insane_proxy_trickery

**Comment by ch3pjw** [comment]
This has been fixed by the dependant Haskell stuff we merged #142 and a few afterwards.
